[package]
name = "mensula_key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.171"
ulid = "1.0.0"
sqlite = { version = "0.31.0", optional = true }

[features]
sqlite = ["dep:sqlite"]
